name: ci_infra

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main

jobs:
  deploy-infra:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up OpenTofu
        uses: opentofu/setup-opentofu@v1

      - name: OpenTofu initialize
        run: tofu init

      - name: OpenTofu validate
        run: tofu validate

      - name: OpenTofu plan
        run: tofu plan

      - name: OpenTofu Apply
        run: tofu apply -auto-approve
